config/routes.rb
Webstore::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "sessions/new"

  resources :products do
     resources :photos
  end
  
  resources :users do
     resources :addresses
  end
  
  resources :sessions,   :only => [:new, :create, :destroy]

  get "user/new"

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"
  
  get "store/index"
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/store',   :to => 'store#index'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><%= link_to "Terms & Conditions", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="span-24">
		<%= link_to logo, root_path %>
	</div>
    <nav class="round">
    	<ul id="nav">
    		<li><%= link_to "Shop Online", store_path(:category => "All") %>
    			<%= render 'menus/shop_menu' %>		
    		</li>
    		<li><%= link_to "Articles", '#' %></li>
    		<li><%= link_to "Contact", contact_path %></li>
	    	<li><%= link_to "About", "#" %></li>
	    	<% if signed_in? %>
	    		<li><%= link_to "Sign out", signout_path %></li>
	    	<% else %>
	    		<li><%= link_to "Sign in", signin_path %></li>
    		<% end %>
    	</ul>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"</script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media=> 'print' %>
<!--[if lt IE8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery.fancybox-1.3.4.css', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<title><%= title %></title>
		<%= javascript_include_tag "application", "nested_form" %>
		<%= render 'layouts/stylesheets' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<div class="field">
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
	</body>
</html>